# Server Configurations
server.port=8080

# Thymeleaf Configurations
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Web Configurations
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/

# ==============================
# Actuator
# ==============================
management.server.port=9090
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.info.env.enabled=true

# ==============================
# Graphite Metrics Export
# ==============================
management.graphite.metrics.export.enabled=true
management.graphite.metrics.export.host=graphite
management.graphite.metrics.export.port=2003
management.graphite.metrics.export.protocol=plaintext
management.graphite.metrics.export.step=10s

# Metric Tags
management.metrics.tags.application=studio
